package org.evgem.android.drachukeugenesapp.ui.activity.launcher

import android.support.v7.widget.RecyclerView
import android.view.LayoutInflater
import android.view.ViewGroup
import org.evgem.android.drachukeugenesapp.R
import org.evgem.android.drachukeugenesapp.ui.base.AutoGeneratedRecyclerAdapter
import org.evgem.android.drachukeugenesapp.util.getRandomColor

class LauncherRecyclerAdapter(itemCount: Int) : AutoGeneratedRecyclerAdapter<LauncherRecyclerViewHolder>(itemCount) {
    override fun onCreateViewHolder(container: ViewGroup, type: Int): LauncherRecyclerViewHolder {
        val view = LayoutInflater.from(container.context).inflate(R.layout.item_launcher_icon, container, false)
        return LauncherRecyclerViewHolder(view)
    }

    override fun onBindViewHolder(item: LauncherRecyclerViewHolder, pos: Int) {
        item.bind(getRandomColor())
    }
}