package org.evgem.android.drachukeugenesapp.ui.base

import android.support.v7.widget.RecyclerView

abstract class AutoGeneratedRecyclerAdapter<VH : RecyclerView.ViewHolder>(private var itemCount: Int) :
    RecyclerView.Adapter<VH>() {
    override fun getItemCount(): Int = itemCount

    fun setItemCount(itemCount: Int) {
        this.itemCount = itemCount
    }
}